apiVersion: v1
kind: Service
metadata:
  name: processing-pipeline-service
spec:
  selector:
    app: processing-pipeline
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
